# Generated by Django 5.0 on 2024-02-01 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
