# Generated by Django 5.0 on 2024-02-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='catFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
