# Generated by Django 5.0 on 2024-02-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_catfields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='catFields',
        ),
    ]
