# Generated by Django 5.0 on 2024-02-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_delete_catfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='logoFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
