# Generated by Django 5.0 on 2024-02-01 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_logofields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logoFields',
        ),
    ]
